name: radio_player
# flutter pub publish
publish_to: "none"
version: 0.2.0+2


environment:
  sdk: ">=3.2.6 <4.0.0"


# flutter pub outdated
dependencies:
  audio_service: ^0.18.13
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4
  flutter_secure_storage: ^9.0.0
  http: ^1.2.0
  just_audio: ^0.9.37
  just_audio_windows: ^0.2.1
  nextcloud_login_flow_v2:
    path: ./nextcloud_login_flow_v2
  url_builder: ^2.0.0


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


# dart run flutter_launcher_icons
flutter_launcher_icons:

  image_path: "assets/icon_1024-1024.jpg"

  android: true
  adaptive_icon_background: "#0082C9"                   # only available for Android 8.0 and above (about 95% of all devices)
  adaptive_icon_foreground: "assets/icon_adaptive.png"  # only available for Android 8.0 and above (about 95% of all devices)

  ios: false

  macos:
    generate: false

  web:
    generate: false

  windows:
    generate: true
    icon_size: 48
    image_path: "assets/icon_windows.png"


# dart run flutter_native_splash:create
flutter_native_splash:

  color: "#0082C9"
  image: "assets/icon_1024-1024.jpg"

  android: true
  android_12:
    color: "#0082C9"
   #image: not specified -> launcher icon is used

  ios: false

  web: false
